### PR TITLE
amend test plan by board

### PR DESCRIPTION
**Pull request by chase-qi**
* amend Ethernet interface
* Remove disk partitioning test on board in blacklist

Signed-off-by: Chase Qi <chase.qi@linaro.org>

### CODE REVIEW

**Comment by danrue** [comment]
This is a good start. I have two thoughts:
- The host-specific configuration should live in the inventory of the playbook, and not in this role. It should be passed into this role as a variable. i.e. erp_network_interface and erp_scratch_disk
- These host-specific variables, if set, could then be passed into the test-runner.py call.

That second part is the part I'm not sure how to do. This is a suggestion but it seems quite long and perhaps messy. Implement -m to pass in parameters to test-runner:
```sh
test-runner -p plans/erp/erp-ltp.yaml -m "automated/linux/network-basic/network-basic.yaml:INTERFACE:eth0" -m "automated/linux/disk-partitioning/disk-partitioning.yaml:DEVICE:/dev/sdb"
```

Inside test-runner, it would overlay any parameters specified on the command line, for the test specified, rather than using the values specified in the yaml file itself.

In this role, then, run_erp_suite.sh would have something like:
```sh
    test-runner -o ${output_path} \
                -p ${plan} \
                {% if erp_network_interface %}-m "automated/linux/network-basic/network-basic.yaml:INTERFACE:{{erp_network_interface}}" \{% endif %}
                {% if erp_scratch_disk %}-m "automated/linux/disk-partitioning/disk-partitioning.yaml:DEVICE:{{erp_scratch_disk}}" \{% endif %}
                > ${output_path}/test-runner-stdout.log \
                2> ${output_path}/test-runner-stderr.log
```

Thoughts?

**Comment by chase-qi** [comment]
I agree that inline yaml update is painful, I spent a while to debug a iteration issue...

It is probably a good idea to update test_list in test-runner with board-specific parameters. I have an idea and gonna give it a try.

**Comment by chase-qi** [comment]
Dan, I have updated this patch, would you please review it again? BTW, it depends on https://review.linaro.org/#/c/22718/

**Comment by danrue** [comment]
Looks good to me :shipit:

**Pull request merged**
